### ISSUE TITLE
A ?q=[UUID] with a refrences to an UUID Postgres DB field doesn't work.

### ISSUE THREAD

**Issue by Ttommeke** [dimitrydhondt/sri4node#107]
Hi all!

I have a resource /articles with the following fields:
content           TEXT,
  poweredby         UUID,
  movie             TEXT,
  author            UUID,
  key               UUID PRIMARY KEY,
  "$$meta.deleted"  BOOLEAN                  NOT NULL DEFAULT FALSE,
  "$$meta.modified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
  "$$meta.created"  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp

All filters work except for the powerdby and author field. When i change the field type in my DB to TEXT instead of UUID suddenly the filters also work for poweredby and author.

Output of /articles?author=UUID(that matches with only 1 article) with UUID type for Author => all records in Article DB
Output of /articles?author=UUID(that matches with only 1 article) with TEXT type for Author => Only single Article wher the author matches.

**Comment by mrft** [comment]
Probably related:

why doesn't ?key= work out of the box like any other property in sri4node (including keyContains etc.)?

(keys= would even be more useful, cfr. hrefs= but shorter)
