### ISSUE TITLE
Fix security on ?expand

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#12]
Currently, the secure functions are not taken into account when specifying expansion on resources. This is a security breach. It should return 403 if the client lacks permission on *any* of the expanded resources.

**Comment by dimitrydhondt** [comment]
Rodro : This should also be taken into account in the secure cache implementation.

**Comment by rodrigouroz** [comment]
Good call. Let's discuss it when we have our conversation this week about the new security module.
