### ISSUE TITLE
Implement a functions for the generalized simple query syntax

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#14]
As described in https://docs.google.com/document/d/1nONjSCZ5P7vybqgVtUFqgWXPUJY8DvRSeo5lXcNTzy0/edit#heading=h.f8ruvmtubm9k

GET /items?firstNameNotCaseSensitiveLike=ike
GET /items?firstName=mike
GET /items?firstNameNot=mike
GET /items?firstNameCaseSensitive=Mike
GET /items?publicationDateBefore=2015-01-10
GET /items?publicationDateContains=2015-04-01
GET /items?tagsContains=news
GET /transactions?amountLessEqual=0
GET /transactions?amountGreater=100000

A single function should be able to detect the operator + operator prefixes.
A second function should allow the client to implement the 'q' parameter easily, by specifying the columns on which to match. (Match case-insensitive, substring on any of the configured columns)

**Comment by dimitrydhondt** [comment]
I've started to implement a cache on the information_schema, allowing the final implementation of 'defaultFilter' to determine adequate operations based on input and the type of the target column.

**Comment by dimitrydhondt** [comment]
I've checked-in a first version of the cache of the information schema. It's in js/informationSchema.js and tests go in test/testInformationSchema.js

**Comment by dimitrydhondt** [comment]
I've checked in a skeleton js/defaultFilter.js and tests in test/testDefaultFilter.js.
I'll integrate a mechanism to register a "default" query parameter.

I.E. If the "query" section of the sri4node configuration registers a "default" function, then I'll call the registered function for any parameter that was not handled explicitly by any other query function.

**Comment by rodrigouroz** [comment]
I've already finished this implementation together with several unit tests. I'll mark this as closed but please let me know if you encounter a wrong or unexpected result.
