### ISSUE TITLE
Creating a Schema is needed before executing sql test script

### ISSUE THREAD

**Issue by xpitr256** [dimitrydhondt/sri4node#18]
I think it is missing the following line at the begining of the schema.sql file:

CREATE SCHEMA sri4node AUTHORIZATION sri4node;

otherwise this line: 

SET search_path TO sri4node; 

Will produce:

no schema has been selected to create in SQL state: 3F000

Thanks,
Pablo

**Comment by dimitrydhondt** [comment]
This is solved in the install scripts.
