### ISSUE TITLE
Show registered resources on root index

### ISSUE THREAD

**Issue by rodrigouroz** [dimitrydhondt/sri4node#22]
Register a route to index ("/") that shows a list of the registered resources such as:

```json
{
  content: {
    href: "/content"
  },
  relations: {
    href: "/relations"
  }
}
```

**Comment by dimitrydhondt** [comment]
We should also think on how we can generate docs from the configuration..

**Comment by dimitrydhondt** [comment]
I've created a separate issue for the docs.

**Comment by dimitrydhondt** [comment]
Maybe we can use the description in the schema to document in this root access ?
And perhaps also point to the documentation ?

That way is is machine consumable, but still remains readable (it is, after all, the root - the most obvious place to start)

**Comment by dimitrydhondt** [comment]
[
  {
    "description": "A list of schools known to VSKO",
    "docs": "/schools/docs",
    "schema": "/schools/schema",
    "href": "/schools"
    ...
  }
]

Rodri, what do you think ?

**Comment by rodrigouroz** [comment]
Love it. Will do it this way.

Of course the link to "docs" will be there but it will only work when that issue is done.

I'll put them both in the same milestone.

**Comment by dimitrydhondt** [comment]
We can't really do this on the root index, as it is too intrusive.
But we could serve it on /resources ? What do you think Rodri ?
Gunther, Can you do this in one swoop with the documentation issue ?

Thanks :-)

**Comment by rodrigouroz** [comment]
/resources sounds fine.

I just want a way to be able to discover an API if you don't know it's resources. Then from then you can see which resources are registered, check their schema, and so on...
