### ISSUE TITLE
Mocha tests failing

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#25]
When I run npm test, 9 tests are failing.

**Comment by dimitrydhondt** [comment]
Need to investigate if this is on my local environment only..

**Comment by rodrigouroz** [comment]
Have you run 'nom update' recently?

**Comment by rodrigouroz** [comment]
Any news on this?

**Comment by dimitrydhondt** [comment]
I've isolated the first failing test : 

it('should find resources case sensitive', function () {
          return doGet(base + '/alldatatypes?textCaseSensitiveGreater=Test').then(function (response) {
            console.log(response.body);
            console.log(response.body.results[0].$$expanded);
            console.log(response.body.results[1].$$expanded);
            assert.equal(response.statusCode, 200);
            assert.equal(response.body.results.length, 4);
            assert.equal(response.body.results[0].$$expanded.text, 'Value');
          });
        });

I am getting the records with text "VSKO" and "Value" (2 records).
When I look in the table these values on column "text" exist : 

"Value"
"A value with spaces"
"VSKO"
"dienst informatica"
"combined unit"

The test tries to do a case sensitive "greater than" selection.

It expects 4 values to be returned.

I think the failure is correct. Only 2 values "VSKO" and "Value" have a case insensitive sort order > "Test"

**Comment by rodrigouroz** [comment]
When I run this query: "select * from alldatatypes where text > 'Test'"

I get 4 results since uppercase letters come before lowercase letters. It might be a problem with the database collation?

So "dienst informatica" > "Test" and "combined unit" > "Test"

**Comment by dimitrydhondt** [comment]
So what's the conclusion on this then ? As far as I can see the resultset should be 2 items, right ?
Am I correct in thinking your database collation is causing this ?

**Comment by rodrigouroz** [comment]
It's a combination of both locale and collation. In the create script, that we both use because it's in the repository, there's no specific collation.

What's the output of 'psql -l' in your computer?

Mine:

    Name     |    Owner    | Encoding |   Collate   |    Ctype    |      Access privileges      
-------------+-------------+----------+-------------+-------------+-----------------------------
 postgres    | rodrigouroz | **UTF8**     | **en_US.UTF-8** | **en_US.UTF-8** |

**Comment by dimitrydhondt** [comment]
codehawk@dimi-laptop:~/workspace/inner-gerbil$ sudo sudo -u postgres psql -l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(3 rows)

**Comment by rodrigouroz** [comment]
So we have the same...

And when you run "select * from alldatatypes where text > 'Test'" you only get two results?

**Comment by dimitrydhondt** [comment]
yes : 

"Value" and "VSKO"

Which seems normal to me ?

**Comment by rodrigouroz** [comment]
Then why on earth with the same locale I also get "dienst informatica" and "combined unit"?

**Comment by dimitrydhondt** [comment]
I would assume that collation would place lower case strings before upper case ?

**Comment by rodrigouroz** [comment]
I know, but I don't know how to fix this and what is causing it.

This query returns empty (so there's no table with a specific different collation than database's)
```sql
select table_schema, 
       table_name, 
       column_name,
       collation_name
from information_schema.columns
where collation_name is not null
order by table_schema,
         table_name,
         ordinal_position;
```

And this query returns "en_US.UTF-8"
```sql
select datname, 
       datcollate
from pg_database;
```

**Comment by rodrigouroz** [comment]
I investigated this further:

https://github.com/PostgresApp/PostgresApp/issues/216

There's known problem in OS X.

I would suggest that someone else fixes the tests that fail and I'll live with them failing for me.

I can't fix them myself because my sorting is wrong (check the comments in the issue for details).

**Comment by rodrigouroz** [comment]
I confirmed with @eznibe and he has the same results as you, so it's definitely an OS X issue.

**Comment by dimitrydhondt** [comment]
Rodri, my tests are running fine now for a while. Is this resolved ? If so can you close the issue ?

Thanks,

Dimi

**Comment by rodrigouroz** [comment]
They work for me too :-)
