### ISSUE TITLE
Fix DELETE operation

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#27]
Right now it issues a sql DELETE on the database. SRI specifies a mechanism of disabling the resource (and allows for retrieval of deleted items).
A mandatory database column "deleted" must be added.
By default the query must also add in the WHERE clause 'WHERE deleted = false'
The deleted flag should appear in $$meta "deleted: true", when it is true

**Comment by rodrigouroz** [comment]
This implies that the client of the module must have had defined the 'deleted' column.

How should the application behave if such column is not available? What kind of error should it generate?

**Comment by dimitrydhondt** [comment]
A message clear enough for the developer to understand what he needs to do..

Perhaps the column should have a more unique name like "sri-delete" ?

In any case it must be treated separatly from the other columns.

**Comment by rodrigouroz** [comment]
How should the deleted resources appear in lists? Only when the filter 'deleted=true' is present?

If you ask directly a deleted resource you get a 409 (Gone) response? or you can still see it?

I also assume that when the query is with 'modifiedSince', those resources are present (with deleted=true in the $$meta section).

**Comment by dimitrydhondt** [comment]
It should be clear from the SRI spec. Tell me if anything is not clear.
https://github.com/dimitrydhondt/sri#resource-removal
