### ISSUE TITLE
NULL values and defaultFilter

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#30]
When a column is NULL, and an operator + prefix "Not" is applied via a sri-query expression ($q.defaultFilter), then the resource with that key == NULL is filter out.

The default behaviour should be to include resources that do not contain the key on which exclusion is being applied.

Other operators probably have similar issues.

**Comment by dimitrydhondt** [comment]
@rodrigouroz and @feelitloveit is this issue resolved now ? or not yet ?

**Comment by rodrigouroz** [comment]
Not yet.

**Comment by rodrigouroz** [comment]
I would fix this for Not, NotIn and NotContains. The other cases are not clear (is NULL Greater or Lower than something?).
