### ISSUE TITLE
Filtering on numeric and strint values seems to fail in $q.defaultFilter

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#32]
When I do 

/resource?balance=20

I am getting all items, also with balance = 0, or balance = -10, etc..

The default filter is configured, but seems to fail on columns of type INTEGER and BIGINT

Dimi

**Comment by rodrigouroz** [comment]
It's working for fields of type 'numeric'. I will create fields of type 'integer' and 'bigint' and check what's going on.

**Comment by rodrigouroz** [comment]
Right now is only checking for fields of type 'numeric'. Extend it to be 'integer' and 'bigint' as well.

**Comment by rodrigouroz** [comment]
@dimitrydhondt should we strive to support ALL numeric types as described here?
http://www.postgresql.org/docs/9.4/static/datatype-numeric.html

Or numeric, integer and bigint are good enough for now?

**Comment by dimitrydhondt** [comment]
I would add all numeric datatypes..

**Comment by rodrigouroz** [comment]
Extension not only to support all the numeric types but also all the string types
