### ISSUE TITLE
sri4node cache not working

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#33]
I have added caching on one of my resource 

cache: {ttl:60, type: 'local'}

But I see no difference in timing (no speedup).

When I add tracing in responseHandler in handleResponse, after res.send(value.data) I see that this point is never hit.

When I add tracing in responseHandler right after store(req.originalUrl, cacheStore, req, res, mapping); -> I see that all my responses trigger 'store', but somehow I never get a cache hit.

**Comment by dimitrydhondt** [comment]
I must have made a mistake, now it is caching. No idea what went wrong here.

**Comment by rodrigouroz** [comment]
Great timing, I was about to start looking at it :-)

**Comment by dimitrydhondt** [comment]
Nope, it seems to work sometimes, and fails other times. Looks like a race-condition...

**Comment by rodrigouroz** [comment]
In which project are you doing this?
What are the steps to reproduce it?

**Comment by rodrigouroz** [comment]
Does it work for you in this project?
You can start sri4node with 'node index.js' and the resource 'alldatatypes' uses cache local.

**Comment by dimitrydhondt** [comment]
I think I've fixed it.
I replaced the Q.all() -> Q.allSettled
The latter allways waits for all 3 caches to give a return value.

**Comment by dimitrydhondt** [comment]
if (cache) {
      Q.allSettled([cacheStore.resources.get(req.originalUrl), cacheStore.list.get(req.originalUrl),
        cacheStore.custom.get(req.originalUrl)]).done(function (results) {
          handleResponse(results[0].value || results[1].value || results[2].value);
        });
    } else {
      handleResponse();
    }

**Comment by dimitrydhondt** [comment]
Now it behaves consistently. It seemed to depend on random timing. If I added some logging it would work, when I removed the logging it failed again, etc..

**Comment by dimitrydhondt** [comment]
I'm now getting consistent 1-2 ms response-times on all my resources. Wonderful !

**Comment by dimitrydhondt** [comment]
Q.all and Q.allSettled are very similar, and as far as I know the only difference would appear if one of the promises would reject. Maybe I need to add logging on rejections
