### ISSUE TITLE
Add server performance monitoring

### ISSUE THREAD

**Issue by rodrigouroz** [dimitrydhondt/sri4node#35]
Allow to log response times for each request and then to parse the results.
Define further...

**Comment by dimitrydhondt** [comment]
It should also create summaries. Like JAMon.

**Comment by dimitrydhondt** [comment]
Rodri, I guess this is done now with the instrumentation ?

If so, please document on how to enable detailed logging in README.md (if you have not done so already), and close the ticket. Ok ?

**Comment by rodrigouroz** [comment]
It's a start, I'm not sure is good enough, but it provided me good insights about what was going on.

It only times GET requests.

I will close it so that we can create a new issue later if we have a new need.
