### ISSUE TITLE
Support modifiedSince queries

### ISSUE THREAD

**Issue by rodrigouroz** [dimitrydhondt/sri4node#39]
Any list should support the filter modifiedSince=timestamp.

This should return only the resources that have been updated after that timestamp.

Therefore on every update, a column named 'modified' must be updated with the current timestamp.

**This enforces clientes of this module to always have a column name "modified" of type timestamp.**

**Comment by dimitrydhondt** [comment]
Yes, we should enforce a deleted column and modified & created column.

Dimi

**Comment by rodrigouroz** [comment]
Dimi

We should do this as soon as possible since our applications are relying on modifiedSince to do the delta updates.

**Comment by dimitrydhondt** [comment]
Make sure it is well documented, but also that we give a clear message to the developer if either 'modified' or 'created' is missing in the schema...

**Comment by rodrigouroz** [comment]
This breaks the current contract, clients must have reserved column names.
It's moved to 1.2.0
