### ISSUE TITLE
Bug in wrapCustomRouteHandler ?

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#44]
When refactoring the getme function I came across this : 

    function wrapCustomRouteHandler(customRouteHandler, mapping) {
      'use strict';
      return function (req, res) {
        Q.all([pgConnect(postgres, configuration, mapping.getme(req))]).done(function (results) {
          customRouteHandler(req, res, results[0], results[1]);
          results[0].done();
        }
      );
    };
  
I think this is a mistake ? How can pgConnect have a third argument (a promise returned by getme) ??

I think this should be : 

    Q.all([pgConnect(postgres, configuration), mapping.getme(req)])

No ?

**Comment by rodrigouroz** [comment]
Definitely.
