### ISSUE TITLE
rename responseHandlerFn.

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#45]
Rod,

Can you come up with a better name for `responseHandlerFn`. Just about everything in sri4node is handling responses in one way or another. Perhaps call it something that refers to the caching it implements ?

Thx,

Dimi

**Comment by rodrigouroz** [comment]
I had a hard time trying to figure out a good name.

This middleware receives the response (either from database or cache) and before sending it to the client it checks the registered security queries.

How can we summarize that in a name? (I do agree the name is too generic)

**Comment by dimitrydhondt** [comment]
secureCache ?
