### ISSUE TITLE
Release and close resources on error

### ISSUE THREAD

**Issue by rodrigouroz** [dimitrydhondt/sri4node#48]
Implement a finally block in getListResource and getRegularResource to close and release resources if an error is thrown and the normal flow doesn't conclude

**Comment by rodrigouroz** [comment]
I'm closing this issue because I checked the code and the database resource is being released (both in the last successful step as in a fail block).

**Comment by dimitrydhondt** [comment]
Hej Rodri,

We are 100% sure there was a problem in the code. Talk to Eze ok ? He can pinpoint a case where it was happening.

Dimi

**Comment by rodrigouroz** [comment]
According to @eznibe the function sri4node.utils.executeSQL is not releasing the connection on error.

**Comment by rodrigouroz** [comment]
I just checked the method executeSQL.

This method receives as its first parameter the database connection, therefore it should not close it. It's a responsible of the caller.

I'll keep taking a look to see this particular scenario.

**Comment by rodrigouroz** [comment]
@eznibe Let's take a look at this together so that I can debug the specific problem you were facing.

**Comment by rodrigouroz** [comment]
I talked with @eznibe and he is now closing the connection on error. That's the responsible of the client. I'll update the documentation to stress the importance of this.
