### ISSUE TITLE
Add intelligent, gzip-compressed URL cache as Express.js middleware

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#5]
Should first investigate if existing Express.js middleware for GZIP compression is smart enough to skip compression if the response is already compressed.

If this is so, build a cache that can store recently requested resource by URL, and serve from cache if possible. Invalidate the cache in an intelligent way when a PUT/DELETE is received on a resource.

**Comment by rodrigouroz** [comment]
I'll check this out...
