### ISSUE TITLE
Automatically map $$meta columns to the $$meta section of the resource

### ISSUE THREAD

**Issue by rodrigouroz** [dimitrydhondt/sri4node#52]

**Comment by dimitrydhondt** [comment]
Don't forget to document this behaviour in READE. md

**Comment by dimitrydhondt** [comment]
Right now they are appearing the the root of the resource as "$$meta.deleted" : false
...

**Comment by rodrigouroz** [comment]
What do you mean?

They appear in the $$meta section, not in the root of the resource.

This issue means to do it automatically. Right now sri4node only puts the three $$meta fields we currently have, if we add more in the future they won't be added automatically.

**Comment by dimitrydhondt** [comment]
Ah I get it. We had created some tests in sri4node for testing $$meta.deleted as columns, and had mapped them explicitly in the test context. So : my bad - never mind :-)

**Comment by rodrigouroz** [comment]
@feelitloveit is this related to the code you just pushed?
If so you can close this issue.
