### ISSUE TITLE
Document custom routes

### ISSUE THREAD

**Issue by rodrigouroz** [dimitrydhondt/sri4node#60]
Document the custom routes in README.

**Comment by dimitrydhondt** [comment]
Also generalize the possible parameters. Right now it is fixed, but is there a way to allow custom routes to have full control over the URL-pattern they are serving ? Can the handler function then get all parameters ?

**Comment by rodrigouroz** [comment]
Dimi

The handler of the custom route receive the parameters request and response, thus they have access to the request parameters. They also receive an open database connection and the result of the identify function.

I'll update the README to reflect this.
