### ISSUE TITLE
Allow beforeinsert and beforeupdate functions

### ISSUE THREAD

**Issue by rodrigouroz** [dimitrydhondt/sri4node#62]
It would be ideal to implement beforeinsert and beforeupdate to manipulate the resource before inserting it.

For example a use case would be hashing a password in a user object.

**Comment by dimitrydhondt** [comment]
What about on insert and onupdate

Verzonden via Yahoo Mail op Android

Van:"Rodrigo Uroz" <notifications@github.com>
Datum:zo, okt. 4, 2015 om 21:38
Onderwerp:[sri4node] Allow beforeinsert and beforeupdate functions (#62)

It would be ideal to implement beforeinsert and beforeupdate to manipulate the resource before inserting it.

For example a use case would be hashing a password in a user object.

**Comment by rodrigouroz** [comment]
Oh, I overlooked those!

Thanks.
