### ISSUE TITLE
How to implement a sign up mechanism using sri4node?

### ISSUE THREAD

**Issue by rodrigouroz** [dimitrydhondt/sri4node#63]
I'm working on a project and need to implement sign up and sign in.

I have a user resource configured with sri4node, but I can't sign up using sri4node because it requires the user to be authenticated to do a PUT on a resource.

How could we avoid the authentication restriction if the PUT is to a new object?

**Comment by rodrigouroz** [comment]
Any ideas?

My first suggestion is to create a new attribute to mark that new resources can be created anonymously (for sign up processes), but any other request is private.

**Comment by dimitrydhondt** [comment]
Perhaps this : 

Now public: false ensures a user is logged in.

But perhaps that config is not necessary.
Perhaps the "secure" functions simply do their work.

This simplifies things by removing a duplicate config.
So a public resource would simply be : 

secure : []

rather than : 

public: true,
secure : []

Sounds good ?

**Comment by dimitrydhondt** [comment]
That would give you full control on the policy of creation with/without security context, etc..
The secure function would get 'undefined' for 'me' if no user is present ?
We would need a solution for signaling that authentication is required to the HTTP client ...

**Comment by dimitrydhondt** [comment]
In general any function should be able to control the status & headers of the response...

**Comment by dimitrydhondt** [comment]
Or at least some functions should have more control over the response sent back to the client. Right now Johannes is working on implementing a more generic mechanism for controlling the response from the afterupdate/afterread/afterinsert and afterdelete functions. The 'secure' functions could be next on the list.

**Comment by rodrigouroz** [comment]
Great, I'll wait until these changes are in place and then I'll try to come up with a sign up mechanism based on sri4node solely.
