### ISSUE TITLE
A required field was missing but still successful PUT

### ISSUE THREAD

**Issue by biancamullie** [dimitrydhondt/sri4node#67]
example (description is required but missing in body)
PUT http://localhost:5000/deliveryoptions/f7514806-db5c-4a0d-a864-77a58441275c
BODY 
{
   "key": "f7514806-db5c-4a0d-a864-77a58441275c",
   "type": "MAIL",
   "$$meta": {
      "permalink": "/deliveryoptions/f7514806-db5c-4a0d-a864-77a58441275c",
      "created": "2015-10-09T14:31:44.277Z",
      "modified": "2015-10-12T12:02:53.392Z"
   }
}

**Comment by dimitrydhondt** [comment]
Added unit test to cover, sri4node seems ok. I'll investigate in the Store API.
