### ISSUE TITLE
Docs do not show JSON schema specification for elements *in* an array.

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#76]
Example : 

{
$schema: "http://json-schema.org/schema#",
title: "A module that needs access to the API. Administrators can grant access to the information in their group to various modules.",
type: "object",
properties: {
name: {
type: "string",
description: "A short display name for this plugin."
},
description: {
type: "string",
description: "A longer description of the functionality this plugin provides."
},
apikey: {
type: "string",
description: "An API-key used by this plugin. Not readable, can be set only by superadmins.",
pattern: "^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$"
},
permissions: {
type: "array",
description: "An array of permissions the plugin requires",
item: {
type: "string",
enum: [
"create_transactions",
"create_messages",
"create_parties",
"read_messages",
"read_transactions",
"read_parties",
"update_messages",
"update_parties",
"delete_messages",
"delete_parties"
]
}
},
configurationschema: {
type: "string",
description: "A JSON schema that expresses the configuration options of this plugin."
}
},
required: [
"name",
"description",
"apikey",
"permissions"
]
}

**Comment by feelitloveit** [comment]
When using array you need to use items instead of item (don't know if it is an typo)
Now it shows a json dump of the items. Will fix this in next push.
