### ISSUE TITLE
$$meta.created is not guaranteed to be unique

### ISSUE THREAD

**Issue by rodrigouroz** [dimitrydhondt/sri4node#77]
This means the queries with LIMIT and OFFSET can return duplicate entries in different pages.

The solution is to order by $$meta.created, key.

This requires a new index by $$meta.created, key.

**Comment by dimitrydhondt** [comment]
Do you mean someone can insert in between, while paging ? And with order by on created it can only append ? In any case a user can order on his own key if he wants. So there is no way to guarantee a way that does not suffer from insert-while-paging. Besides the fact the the client must accept duplicates (think idempotency)

**Comment by rodrigouroz** [comment]
No. Currently the order was "order by "$$meta.created".

We had in content-api several resources with the same timestamp value for "$$meta.created", exactly the same instant. So the order was not guaranteed to be unique and hence some limit and offset queries returned the same resources in different pages.

The solution is to break with another column, in this case the key.

Is it clear now?

**Comment by rodrigouroz** [comment]
So the default order by is "order by "$$meta.created", "key"
And an index is recommended:
CREATE INDEX table_created_key ON table ("$$meta.created", "key");

**Comment by rodrigouroz** [comment]
Good point. I'm not saying you shouldn't expect duplicates while paging, but this was a generic case where the default order by was not guaranteed to be unique, something that Postgresql highly recommends.

**Comment by dimitrydhondt** [comment]
I think ordering by default on a timestamp + guid is quite heavy. I think some technical row id would be better. We're basically looking to have a stable sort order by default, right ?
There is no specific requirement to do it on "created", I think ?

Some possible system columns : http://www.postgresql.org/docs/8.3/static/ddl-system-columns.html

Ordering on oid could be a better approach ?

**Comment by rodrigouroz** [comment]
Indeed, I thought it would be better from a functional point of view to sort by created. Why using `oid` if we already have a `key` column for each row?

In fact I've been reading and people discourage the use of `oid` for sorting.

What we can do is adapt it to sort by the primary key (`key`) but the default order of the list will change upon each new resource on the list.

What do you think?

**Comment by rodrigouroz** [comment]
Such as here: http://www.postgresql.org/message-id/264855a01003240529n48c4b3cet922c7a471464743c@mail.gmail.com

**Comment by rodrigouroz** [comment]
And the specification says it doesn't guarantee uniqueness (which is the main root of the problem we're trying to solve on this issue, if the sort criteria is not unique, then the pagination might return the same resource on different pages): http://www.postgresql.org/docs/9.4/static/datatype-oid.html

**Comment by dimitrydhondt** [comment]
My initial fear was that GUID was too long, and thus slow for sorting. But I guess because we use the GUID type, it should be fast, right ? In that case the key seems a better option. 

That said, what was the reason you would not use the default order (unspecified) by the database ?
It is unspecified, but stable, as far as I know..

**Comment by rodrigouroz** [comment]
Because of this: http://www.postgresql.org/docs/9.4/static/queries-limit.html

> When using LIMIT, it is important to use an ORDER BY clause that constrains the result rows into a unique order. Otherwise you will get an unpredictable subset of the query's rows. You might be asking for the tenth through twentieth rows, but tenth through twentieth in what ordering? The ordering is unknown, unless you specified ORDER BY.

**Comment by dimitrydhondt** [comment]
Key seems te natural choice here.

**Comment by rodrigouroz** [comment]
Ok, so that means the default order by should be:

`order by key` 

and nothing else?

**Comment by rodrigouroz** [comment]
Is this for performance issues or for a functional requirement?

Because if this is for performance issues, in the README we suggest the clients to create an index for the sorting:

The following index is for the default order by:

* CREATE INDEX table_created_key ON *table* ("$$meta.created", "key");

**Comment by rodrigouroz** [comment]
And if there's no performance penalty if we sort by created and key, the sorting is constant, it will always be the same since created is a constant field that doesn't change, thus the paging is also constant.

That was my rationale when I chose these fields.

**Comment by dimitrydhondt** [comment]
K. Better on created  (desc  ?) and then on key.
