### ISSUE TITLE
[Performance improvement] - Slow count

### ISSUE THREAD

**Issue by rodrigouroz** [dimitrydhondt/sri4node#78]
Postgresql suffers from a slow performance on count queries: https://wiki.postgresql.org/wiki/Slow_Counting

Each list query performs a count on the table for the meta information of the result.

Since the resource is controlled by sri4node (changes to the resource are handled by it), we could cache the result of the count and avoid an extra query for each list query, only issuing a new count when a modification to the resource is done (any PUT invalidates the count).

**Comment by rodrigouroz** [comment]
Example from an actual resource (content), using index-only-scan:

```
Aggregate  (cost=20315.65..20315.66 rows=1 width=0) (actual time=538.507..538.507 rows=1 loops=1)
   ->  Index Only Scan using content_deleted on content  (cost=0.08..20152.00 rows=327314 width=0) (actual time=0.091..480.425 rows=327314 loops=1)
         Index Cond: ("$$meta.deleted" = false)
         Filter: (NOT "$$meta.deleted")
         Heap Fetches: 131249
 Planning time: 0.111 ms
 Execution time: 538.559 ms
```

**Comment by rodrigouroz** [comment]
Example without any filter:
```
vsko-content-api-test::DATABASE=> explain analyze select count(*) from "content";
                                                                     QUERY PLAN                                                                     
----------------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=20152.00..20152.00 rows=1 width=0) (actual time=476.086..476.086 rows=1 loops=1)
   ->  Index Only Scan using content_deleted on content  (cost=0.08..19988.34 rows=327314 width=0) (actual time=0.076..418.001 rows=327314 loops=1)
         Heap Fetches: 131249
 Planning time: 0.089 ms
 Execution time: 476.130 ms
(5 rows)
```

**Comment by dimitrydhondt** [comment]
I think Matthias had a solution to avoid a separate count(*) query. @matthiassnellings ?

**Comment by rodrigouroz** [comment]
That would be great. I'll wait for his remarks.

**Comment by rodrigouroz** [comment]
@matthiassnellings have you seen this?

**Comment by rodrigouroz** [comment]
Does this include doing a join or something like that?

If we don't get a response I would assume there's no other way and will use the cache.

**Comment by matthiassnellings** [comment]
You can do in postgress:
SELECT p.uuid,count(*) over() as total FROM persons p
and total would be available in the resultset.
Easy and fast (you do not lose any performance by adding this)

**Comment by rodrigouroz** [comment]
Cool, I'll improve it as soon as I have some time. I love the idea of saving an extra query on each request.
