### ISSUE TITLE
Should return 201 upon creating a resource with PUT

### ISSUE THREAD

**Issue by sorokh** [dimitrydhondt/sri4node#79]
Conform http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6 SRI4Node should make the distinction between a resource being updated and a resource being created. In the latter case it should properly return 201 (created) instead of 200 (ok), as stated in the spec.

**Comment by dimitrydhondt** [comment]
Yes, you are right. And it actually says 'MUST' ! My bad.

**Comment by dimitrydhondt** [comment]
In fact the SRI spec should be adapted as well.
