### ISSUE TITLE
Add support for conditional GETs

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#9]
Send 304 Not Modified if a GET operation is conditional, and the resource was not modified.

**Comment by rodrigouroz** [comment]
Express is currently doing this by default (by using Etag).

Is this what you're talking about?

**Comment by dimitrydhondt** [comment]
Ah, that could be. Any idea how it generates the Etag ? A hash of the body ?

**Comment by rodrigouroz** [comment]
It has two modes: weak and strong.

An identical strong ETag guarantees the response is byte-for-byte the same, while an identical weak ETag indicates that the response is semantically the same.

strong uses a hash of the entity and weak only a computation on its timestamp (modification time).

The default is weak, we can test with strong or even plug our own etag function.

**Comment by dimitrydhondt** [comment]
Thanks for this info, Rod !

**Comment by rodrigouroz** [comment]
weak: a computation of modified time + size of the entity
strong: md5 of the body (basically, with other things)
