### ISSUE TITLE
?expand=results.xxx does not do proper expansion.

### ISSUE THREAD

**Issue by dimitrydhondt** [dimitrydhondt/sri4node#93]
It seems to return the same result for every item in the list.

https://inner-gerbil-test.herokuapp.com/messages?postedInDescendantsOfParties=%2Fparties%2F8bf649b4-c50a-4ee9-9b02-877aa0a71849&expand=results.author

Notice that for different authors the same $$expanded is returned.

user : annadv
pwd: test

**Comment by dimitrydhondt** [comment]
https://github.com/dimitrydhondt/inner-gerbil

**Comment by rodrigouroz** [comment]
Forgot this issue was created and created a new one (#98).
This is already fixed in #98
