### ISSUE TITLE
403 Forbidden in html

### ISSUE THREAD

**Issue by feelitloveit** [dimitrydhondt/sri4node#97]
When you have a forbidden error you get `<h1>403 Forbidden</h1>`
Since the encoding is set to json this is not correct and will not render as html.

Should we send an html page? or give a json error? @dimitrydhondt

**Comment by dimitrydhondt** [comment]
In line with the rest I would say a json object.

**Comment by rodrigouroz** [comment]
The specification says that on 403 the client should receive 403 status code and nothing more. For security reasons there's nothing else you should say to the client.

I will remove the body for this case and only return status 403, empty body.

**Comment by rodrigouroz** [comment]
https://github.com/dimitrydhondt/sri#handling-security
